import type { Metadata } from "next";
import "../globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import Headers from "../../components/Header";
;


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
    <html lang="en">
    <body>
       <main> 
        <Headers />
        {children} 
        </main>
        </body>
    </html>
    </ClerkProvider>
  );
}
